extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  - vocab.txt
  - extensions.txt
filters:
  - '(?s)We would like to thank the following contributors from the CockroachDB community.*'
